server:
  port: 9000
  contextPath: /services

spring:
  application:
    name: AuthorizationApplication
  zipkin:
    baseUrl: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG

security:
#  user:
#    name: richard
#    password: password
#    role: USER
  oauth2:
    client:
      clientId: pluralsight
      clientSecret: pluralsightsecret
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: toll_read,toll_report
